enc-administrator:
gpg --output devpost-administrator.md.gpg --encrypt --recipient davisjf@gmail.com devpost-administrator.md

dec-administrator_tofile:
gpg --output devpost-administrator.md --decrypt devpost-administrator.md.gpg

dec-administrator_toconsole:
gpg --decrypt devpost-administrator.md.gpg






enc-jfd:
gpg --output devpost-jfd.md.gpg --encrypt --recipient davisjf@gmail.com devpost-jfd.md

dec-jfd_tofile:
gpg --output devpost-jfd.md --decrypt devpost-jfd.md.gpg

dec-jfd_toconsole:
gpg --decrypt devpost-jfd.md.gpg

